# Generated by Test Agent — overwritten each pipeline run
import pytest
import httpx
import os

BASE_URL = os.environ.get("TEST_BASE_URL", "http://localhost:8000")


def test_list_expenses():
    with httpx.Client(base_url=BASE_URL) as client:
        r = client.get("/api/expenses")
        assert r.status_code == 200
        data = r.json()
        assert isinstance(data, list)


def test_expense_summary():
    with httpx.Client(base_url=BASE_URL) as client:
        r = client.get("/api/expenses/summary")
        assert r.status_code == 200
        data = r.json()
        assert "total" in data
        assert "tax_deductible" in data
        assert "by_category" in data
        assert "count" in data


def test_create_expense():
    payload = {
        "title": "Test expense",
        "amount": 42.50,
        "vendor": "Test Vendor",
        "city": "San Francisco",
        "latitude": 37.7749,
        "longitude": -122.4194,
    }
    with httpx.Client(base_url=BASE_URL) as client:
        r = client.post("/api/expenses", json=payload)
        assert r.status_code == 200
        data = r.json()
        assert data["title"] == "Test expense"
        assert data["amount"] == 42.50
        assert "id" in data
        return data["id"]


def test_delete_expense():
    payload = {
        "title": "To be deleted",
        "amount": 1.00,
        "vendor": "Temp",
        "city": "SF",
        "latitude": 37.7,
        "longitude": -122.4,
    }
    with httpx.Client(base_url=BASE_URL) as client:
        create = client.post("/api/expenses", json=payload)
        assert create.status_code == 200
        expense_id = create.json()["id"]

        delete = client.delete(f"/api/expenses/{expense_id}")
        assert delete.status_code == 200

        expenses = client.get("/api/expenses").json()
        ids = [e["id"] for e in expenses]
        assert expense_id not in ids


def test_delete_nonexistent_expense():
    with httpx.Client(base_url=BASE_URL) as client:
        r = client.delete("/api/expenses/99999")
        assert r.status_code == 404


def test_create_expense_validation():
    with httpx.Client(base_url=BASE_URL) as client:
        r = client.post("/api/expenses", json={"title": "missing fields"})
        assert r.status_code == 422
